version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - spring-postgres-net

  app:
    build: .  # Buduje obraz z Dockerfile w bieżącym katalogu
    container_name: my_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - spring-postgres-net

networks:
  spring-postgres-net:
    driver: bridge